# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w95Ytq9_IsLQLehh90XWwlkTmJ_bVGTG

**Step 1: Installing Dependencies**
"""

pip install gradio transformers pillow torch requests

"""** Step 2: Creating a New Python Script**"""

import gradio as gr
import requests
from PIL import Image
from transformers import BlipProcessor, BlipForConditionalGeneration

# Load BLIP Model
processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")

# Function to generate captions
def generate_caption(image):
    try:
        # Process the image
        inputs = processor(images=image, return_tensors="pt")

        # Generate caption
        out = model.generate(**inputs)
        caption = processor.decode(out[0], skip_special_tokens=True)

        return caption

    except Exception as e:
        return f"Error: {str(e)}"

# Gradio Web Interface
interface = gr.Interface(
    fn=generate_caption,
    inputs=gr.Image(type="pil"),
    outputs="text",
    title="🖼️ AI Image Captioning",
    description="Upload an image, and the AI will generate a caption!",
    theme="default"
)

# Run the Gradio App
if __name__ == "__main__":
    interface.launch()

